services:  
  mysql:
    image: mysql:8.0.28
    ports:
      - "3306:3306"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=vitasnap
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql